battery:
  capacity: 1000
  voltage: 6.0
communication:
  agent_info_relevant: 10
  max_jitter: 10
  message_loss_probability: 0
  quadtree_exchange_interval: 15
  time_sync_interval: 5
  wifi_range: 99999
  wifi_speed: 10
confidence:
  alpha_receive: 0.6
  p_at_max_sensor_range: 1.0
  p_free: 0.6
  p_free_threshold: 0.7
  p_max: 0.9
  p_min: 0.05
  p_occupied: 0.35
  p_occupied_threshold: 0.3
control:
  360_degrees_steps: 360
  agent_safety_radius_margin: 0.1
  disallow_frontier_switching:
    feasibility_check_only_route: false
    frontier_reach_distance: 1
    frontier_switch_interval: 5
    target_feasibility_check_interval: 10
  object_safety_factor: 1
  path_planning:
    max_route_length: 30
  separate_frontiers:
    distance_threshold: 1.0
  turn_speed_ratio: 0.1
  turn_threshold: 15
forces:
  agent_alignment_radius: 1
  agent_alignment_weight: 0
  agent_avoidance_radius: 0.5
  agent_avoidance_weight: 1.15
  agent_cohesion_radius: 1.5
  agent_cohesion_weight: 0
  frontier_cell_ratio: 1.0
  frontier_fitness:
    distance_weight: 0
    k: 0.1
    l: 0.8
    m: 2.5
    n: 3
    pheromone_weight: 0.05
    reach_battery_weight: 1.5
    reach_duration_weight: 0.1
    size_weight: 0
  frontier_search_radius: 5
  max_frontier_regions: 20
  object_avoidance_radius_margin: 0.1
  target_weight: 0.3
  virtual_wall_avoidance_weight: 0
mission:
  end_battery_level: 0
  end_time: 400
motor:
  no_load_current: 0.16
  no_load_rpm: 250
  stall_current: 1.5
  stall_torque: 0.8
physical:
  robot_inter_wheel_distance: 0.0565
  robot_radius: 0.0362
  robot_weight: 0.4
  robot_wheel_radius: 0.0205
quadtree:
  evaporated_pheromone_factor: 0.05
  evaporation_time: 100
  merge_max_confidence_diff: 0.05
  merge_max_visited_time_difference: 5
  resolution: 0.28
sensors:
  distance_sensor_jitter: 10
  distance_sensor_noise_factor: 1
  distance_sensor_range: 2
  orientation_jitter: 5
  orientation_noise: 8
  position_jitter: 10
  position_noise: 103.3
